# ================================
# Configuration for Cross-Publication Insight Assistant
# ================================

# Directory Paths
paths:
  output_dir: "output/"
  analyzer_prompt: "config/prompts/analyzer_prompt.txt"
  summarize_prompt: "config/prompts/summarize_project.txt"
  aggregate_prompt: "config/prompts/aggregate_query.txt"

rag_summarizer:
  max_files: 8
  max_file_chars: 4000

#Model / LLM Configuration
llm:
  model_name: "models/phi-2.Q6_K.gguf"
  context_window: 36000
  temperature: 0.2
  type: "local"

# Repo Parser Configuration
repo_parser:
  extension_language_map:
    .py: Python
    .js: JavaScript
    .ts: TypeScript
    .java: Java
    .cpp: C++
    .c: C
    .go: go
    .rs: Rust
    .php: php
    .ipynb: Jupyter Notebook
    .sh: Shell
    .css: css
    .json: JSON
    .yaml: YAML
    .md: Markdown
    .cs: C#
    .rb: Ruby
  max_readme_excerpt_chars: 500
  max_license_excerpt_chars: 200
  num_keywords: 10

# Logging Configuration
Logging:
  level: INFO
  log_file: "output/project.log"

embeddings:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  top_k: 5
  score_threshold: 0.4

hitl:
  enabled: true 
  step: "pre-summary"
